services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: app_db
      MYSQL_USER: alexx
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
